version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /core
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /wazm
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /bin/cli
    schedule:
      interval: weekly
