[package]
authors.workspace = true
categories.workspace = true
default-run = "waz"
description = "waz is a CLI application streamlining development with wazm."
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "wazm-cli"
readme.workspace = true
repository.workspace = true
version.workspace = true

[[bin]]
name = "waz"
path = "src/main.rs"

[build-dependencies]

[dependencies]
anyhow = "1"
serde_json = "1"
smart-default = "0.7"

[dependencies.clap]
features = ["derive", "env"]
version = "4"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.strum]
features = ["derive"]
version = "0.26"

[dependencies.tracing]
features = []
version = "0.1"

[dependencies.tracing-subscriber]
features = []
version = "0.3"

[dependencies.wazm]
features = ["full"]
path = "../../wazm"
# git = "https://github.com/FL03/wazm.git"
# version = "0.0.1"

[dev-dependencies]
