name: binaries

concurrency: 
  cancel-in-progress: false
  group: ${{ github.event.repository.name }}-rust

env:
  CARGO_TERM_COLOR: always
  CRATE_BASENAME: ${{ github.event.repository.name }}

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags: [ v*.*.* ]
  release:
    types: [ created ]
  repository_dispatch:
    types: [ rust ]
  schedule:
    - cron: "30 21 * * 0" # Every Sunday at 9:30pm UTC
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    name: Build (cli)
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        toolchain: [ stable, nightly ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: setup (rustup)
        run: |
          rustup default ${{ matrix.toolchain }}
          rustup update
      - name: setup (cache)
        uses: actions/cache@v4
        with:
          key: bin-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/debug
            target/release
          restore-keys: |
            bin-${{ runner.os }}-cargo-
            bin-cargo-
      - name: build (cli)
        run: |
          cargo build --all-features -p wazm-cli -r -v
          cp target/debug/waz waz
      - name: dry-run (cli)
        run: waz --version
